
import sys, os
from pathlib import Path
from typing import Callable, Iterable, Any

_curSrcPath = Path(__file__)
DEBUG = os.getenv("NPY_UNICODE_DEBUG", "0") == "1"
UNICODES_RANGE = range(sys.maxunicode + 1)

def get_main_script_file():
    main_module = sys.modules.get('__main__')
    
    if main_module and hasattr(main_module, '__file__'):
        return Path(main_module.__file__).name
    
    return None

def gen(fn: str, main: Callable[[], None]):
  with open(_curSrcPath.with_name("unicase_outdir.txt"), encoding="utf-8") as f:
      outdir = f.read().strip()


  if not DEBUG:
    ofile = open((Path(outdir)/fn).with_suffix('.nim'), 'w', encoding='utf-8')
    sys.stdout = ofile
  
  module_name = get_main_script_file()
  if module_name is None:
      module_name = _curSrcPath.name

  print(f"""# Generated by /tools/unicodedata/{module_name}
# where `/` refers to the root path of this project.
# to be included
""")

  main()

  if not DEBUG:
    ofile.close()
    sys.stdout = sys.__stdout__


def gen_map(sym_name: str, itor: Iterable[tuple[Any, Any]]):
  print(f"const {sym_name} = {{")
  for i, s in itor:
     print(f"""  {i}: {s},""")
  print("}")

def gen_array(sym_name: str, itor: Iterable[Any]):
  print(f"const {sym_name} = [")
  for s in itor:
     print(f"""  {s},""")
  print("]")

